#version 450
#include <common.glsl>

// define descriptors
#define DESC_PALETTE 2
#define DESC_TIME 3
#define DESC_ITERATION 5
#define DESC_STRIPE 6
#define DESC_ITERATION_BUFFER_ACCESS writeonly

// include descriptors
#include <desc_iteration.glsl>
#include <desc_palette.glsl>
#include <desc_time.glsl>
#include <desc_stripe.glsl>

// include utilities
#include <utils_iteration.glsl>
#include <utils_palette.glsl>
#include <utils_stripe.glsl>


layout (set = 0, binding = 0) buffer Iteration2MapNormalSSBO {
    double iterations[];
} it2map_normal_settings;

layout (set = 0, binding = 1) buffer Iteration2MapZoomedSSBO {
    double iterations[];
} it2map_zoomed_settings;


layout (set = 1, binding = 0) uniform VideoUBO {
    float default_zoom_increment;
    float current_frame;
} video_settings;

layout (set = 4, binding = 0, rgba8) writeonly uniform image2D merged_image_output;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


double get_iteration_normal(ivec2 iter_coord, ivec2 offset) {
    return it2map_normal_settings.iterations[get_iteration_index(iter_coord, offset)];
}


double get_iteration_zoomed(ivec2 iter_coord) {
    return it2map_zoomed_settings.iterations[get_iteration_index(iter_coord)];
}

void set_iteration_output(ivec2 iter_coord, double value) {
    iteration_settings.iterations[get_iteration_index(iter_coord)] = value;
}


void main() {

    vec2 center = vec2(iteration_info_settings.extent) / 2.0;
    vec2 coord = vec2(gl_GlobalInvocationID.xy) - center;
    float r = int(max(0, video_settings.current_frame)) - video_settings.current_frame;

    float nsr = pow(video_settings.default_zoom_increment, r + 1);// r = 0 ~ 1
    float zsr = pow(video_settings.default_zoom_increment, r);// r = -1 ~ 0

    vec2 ntx = coord / nsr + center;

    ivec2 ntx_i = ivec2(floor(ntx));
    vec2 nrt = fract(ntx);

    double n00 = get_iteration_normal(ntx_i, ivec2(0, 0));
    double n10 = get_iteration_normal(ntx_i, ivec2(1, 0));
    double n01 = get_iteration_normal(ntx_i, ivec2(0, 1));
    double n11 = get_iteration_normal(ntx_i, ivec2(1, 1));

    vec3 nc00 = palette_get_color(n00).rgb * stripe_get_multiplier(n00);
    vec3 nc10 = palette_get_color(n10).rgb * stripe_get_multiplier(n10);
    vec3 nc01 = palette_get_color(n01).rgb * stripe_get_multiplier(n01);
    vec3 nc11 = palette_get_color(n11).rgb * stripe_get_multiplier(n11);

    vec3 nc0 = nc00 - (nc00 - nc10) * nrt.x;
    vec3 nc1 = nc01 - (nc01 - nc11) * nrt.x;
    vec3 nc = nc1 - (nc1 - nc0) * nrt.y;

    double n0 = n00 - (n00 - n10) * nrt.x;
    double n1 = n01 - (n01 - n11) * nrt.x;
    double n = n1 - (n1 - n0) * nrt.y;

    vec2 ztx = coord / zsr + center;
    vec2 ztx_min = max((coord - vec2(0.5, 0.5)) / zsr + center, vec2(0));
    vec2 ztx_max = min((coord + vec2(0.5, 0.5)) / zsr + center, vec2(iteration_info_settings.extent));

    ivec2 ztx_i = ivec2(floor(ztx));
    double z00 = get_iteration_zoomed(ztx_i);

    if (ztx.x >= iteration_info_settings.extent.x - 1 || ztx.y >= iteration_info_settings.extent.y - 1 || ztx.x < 0 || ztx.y < 0 || z00 == 0) {
        set_iteration_output(ivec2(gl_GlobalInvocationID.xy), n);
        imageStore(merged_image_output, ivec2(gl_GlobalInvocationID.xy), vec4(nc, 1));
        return;
    }

    ivec2 ztx_i_min = ivec2(floor(ztx_min));
    ivec2 ztx_i_max = ivec2(ceil(ztx_max));

    double z_sum = 0;
    vec3 zc_sum = vec3(0);
    float w_sum = 0;

    ztx_i.y = ztx_i_min.y;

    while (ztx_i.y < ztx_i_max.y) {
        ztx_i.x = ztx_i_min.x;

        while (ztx_i.x < ztx_i_max.x) {
            vec2 w = min(min(ztx_i + ivec2(1, 1) - ztx_min, ztx_max - ztx_i), vec2(1, 1));
            float weight = w.x * w.y;

            double z_temp = get_iteration_zoomed(ztx_i);
            vec3 zc_temp = palette_get_color(z_temp).rgb * stripe_get_multiplier(z_temp);
            z_sum += z_temp * weight;
            zc_sum += zc_temp * weight;
            w_sum += weight;
            ++ztx_i.x;
        }
        ++ztx_i.y;
    }

    double z = z_sum / w_sum;
    vec3 zc = zc_sum / w_sum;

    set_iteration_output(ivec2(gl_GlobalInvocationID.xy), z);
    imageStore(merged_image_output, ivec2(gl_GlobalInvocationID.xy), vec4(nc * (-r) + zc * (r + 1), 1));

}