#!/bin/bash

set -e

version="$1"
desc="$2"

if [[ ! "$version" == v* ]]; then
    echo -e "\033[31mIllegal Version selection : '$version'\033[0m"
    exit 1
fi

if [[ -z "$desc" || "$desc" =~ ^[[:space:]]*$ ]]; then
    echo -e "\033[31mIllegal Description : '$version'\033[0m"
    exit 1
fi

echo -e "\033[36mCommitting with message: '$desc' and tagging version: '$version'\033[0m"

git add .

git commit -m "\"$desc\""

git push

git tag "$version"

git push --tags

archive="RFF.zip"

if [[ -f "$archive" ]]; then
    rm "$archive"
fi

zip -r "$archive" "installer_linux_ubuntu.sh" "installer_windows.bat" "installer_windows_bootstrap.ps1"

gh release create "$version" "$archive" --generate-notes --latest

rm "$archive"